version: '3.1'

services:

  testrunner:
    image: $DEV_IMAGE_TAG
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        ELIXIR_VERSION: $ELIXIR_VERSION
    volumes:
      - .:$PWD
    environment:
      - MIX_ENV=test
    depends_on:
      db:
        condition: service_healthy
    working_dir: $PWD

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apikeymgmt
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
