ARG ELIXIR_VERSION
ARG OTP_VERSION

FROM docker.io/library/elixir:${ELIXIR_VERSION}-otp-${OTP_VERSION}
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Set env
ENV CHARSET=UTF-8
ENV LANG=C.UTF-8

# Set runtime
CMD ["/bin/bash"]
